name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-container:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build.outputs.image }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          credentials_json: ${{ secrets.DEPLOYER_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker gcr.io

      - name: Build Container Image
        id: build
        run: |
          cd functions
          IMAGE_TAG="gcr.io/home-assistant-mobile-apps/mobile-push:${{ github.sha }}"
          gcloud builds submit --tag $IMAGE_TAG
          echo "image=$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy-cloud-run:
    needs: build-container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          credentials_json: ${{ secrets.DEPLOYER_SERVICE_ACCOUNT }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@2028e2d7d30a78c6910e0632e48dd561b064884d # v3.0.1
        with:
          service: mobile-push
          image: ${{ needs.build-container.outputs.image }}
          region: us-central1
          flags: |
            --allow-unauthenticated
            --vpc-connector=${{ secrets.VPC_CONNECTOR }}

  deploy-hosting:
    needs: deploy-cloud-run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@19d0a485d5819ca458411f9eb3562b1e2882c7ea # v15.22.0
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.DEPLOYER_SERVICE_ACCOUNT }}
