name: test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  functions:
    runs-on: ubuntu-latest
    env:
      working-directory: functions/
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
      working-directory: ${{ env.working-directory }}
    - name: Run tests
      run: npm test
      working-directory: ${{ env.working-directory }}
    - name: Run lint
      run: npm run lint
      working-directory: ${{ env.working-directory }}
    - uses: codecov/codecov-action@v1
      name: "Upload Code Coverage"
      with:
        files:  ${{ env.working-directory }}/coverage/lcov.info

