name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  functions:
    runs-on: ubuntu-latest
    env:
      working-directory: functions/
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install
      working-directory: ${{ env.working-directory }}
    - name: Check code formatting
      run: npx prettier --check "**/*.{js,ts,jsx,tsx}"
      working-directory: ${{ env.working-directory }}
    - name: Run tests with coverage
      run: npm run test:coverage
      working-directory: ${{ env.working-directory }}
    - name: Run lint
      run: npm run lint
      working-directory: ${{ env.working-directory }}
    - uses: codecov/codecov-action@v5
      name: "Upload Code Coverage"
      with:
        files:  ${{ env.working-directory }}/coverage/lcov.info

